### PR TITLE
Update App.config

### PR DESCRIPTION
**Pull request by uniqueitmail**
Please update this project to connect remote server database, Now it is not work for remote server but local server worked fine as well project. But now need to change and make it for remote server database with User ID & Password to connect remote server, Thank you.

### CODE REVIEW

**Comment by uniqueitmail** [comment]
**OK FOR LocalServer**
`<add name="ConnectionString" connectionString="Integrated Security=SSPI;Pooling=false;Data Source=.; User ID=sa;Password=1; Initial Catalog=RuntimeDbChooser" />`

 **### For Remote Server...? _Need Help For REMOTE SERVER Database_ -This Project...???**
`<add name="ConnectionString" connectionString="Integrated Security=false;Pooling=false;Data Source=161.151.141.253; User ID=sa;Password=1; Initial Catalog=RuntimeDbChooser" />`

> **??? Remote Server Connection for this current project....????**

**Comment by AndreyKozhevnikov** [comment]
Hello,
 
You can read more about connection strings in .NET solutions here: [Connection Strings and Configuration Files | Microsoft Docs](https://docs.microsoft.com/en-us/dotnet/framework/data/adonet/connection-strings-and-configuration-files)
If you face any difficulties with connecting your XAF app to a database, create a ticket in our Support Center and we will assist there.
 
Thanks,
Andrey

**Comment by uniqueitmail** [comment]
> **REQUEST_TO: HELP _WANTED_**

ConnectionString  - remote database with MSSQL command please write in App.config
with current ConnectionString - Local to Remote/Azure  database.

#XAF_how-to-change-connection-to-the-database-at-runtime-e1344

**Remote Server Database Not Work: Solution Please of your project::**
`<add name="ConnectionString" connectionString="Integrated Security=false;Pooling=false;Data Source=161.151.141.253; User ID=sa;Password=1; Initial Catalog=RuntimeDbChooser" />`

Please write about Remote Database with MSSQL on App.config  - Inside will be E1344  - What am I wrong with this ConnectionString...

_Thank you._

**Comment by AndreyKozhevnikov** [comment]
Hello,

If you need further technical assistance, please submit a ticket to our Support Center and describe the issue in greater detail. We will be happy to help you. 

Thanks,
Andrey

**Pull request closed without merging**
